apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod
spec:
  containers:
    - name: two-tier-app
      image: nahid0002/flask-app:latest
      env:
        - name: MYSQL_HOST
          value: "10.101.141.26" #mysql
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_DB
          value: "mydb"
      ports:
        - containerPort: 5000
      imagePullPolicy: Always