apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod
spec:
  containers:
    - name: two-tier-app
      image: nahid0002/flask-app:latest
      env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_DB
          value: myDb
      ports:
        - containerPort: 5000
      imagePullPolicy: Always